name: counter
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: "^3.9.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/image1.png
    - assets/image2.png
